---
version: '3'

volumes:
  prom-data: {}
  grafana-data: {}

services:
  prometheus:
    image: prom/prometheus:v2.20.0
    restart: unless-stopped
    command:
      - '--config.file=/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/prometheus.yaml:ro
      - prom-data:/prometheus

  grafana:
    image: grafana/grafana:7.1.3
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning:ro
      - ./grafana/provisioning/dashboards/:/var/lib/grafana/dashboards:ro

  nodeexporter:
    image: prom/node-exporter
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.cpufreq'
      - '--collector.diskstats'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.hwmon'
      - '--collector.loadavg'
      - '--collector.meminfo'
      - '--collector.netclass'
      - '--collector.netstat'
      - '--collector.stat'
      - '--collector.uname'
      - '--collector.vmstat'
      - '--collector.wifi'
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
