---
volumes:
  prom-data: {}
  grafana-data: {}

networks:
  caddy:
    external: true

services:
  prom:
    image: prom/prometheus:${PROM_VERSION}
    restart: always
    command:
      # - '--log.level=debug'
      - '--config.file=/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus/prom'
      - '--storage.tsdb.retention.time=4w'
      - '--web.enable-admin-api'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/prometheus.yaml:ro
      - ./secrets/:/secrets:ro
      - prom-data:/prometheus
    extra_hosts:
      home.mafro.net: 192.168.1.198
      locke: 192.168.1.198
      jorg: 192.168.1.104

  prom-lts:
    image: prom/prometheus:${PROM_VERSION}
    restart: unless-stopped
    command:
      - '--config.file=/dev/null'   # No configuration file
      - '--storage.tsdb.path=/prometheus/lts'
      - '--storage.tsdb.retention.time=10y'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9091:9090
    volumes:
      - prom-data:/prometheus
    depends_on:
      - prom

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    restart: unless-stopped
    networks:
      - caddy
      - default
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning:ro
      - ./grafana/provisioning/dashboards/:/var/lib/grafana/dashboards:ro
    extra_hosts:
      locke: 192.168.1.198
    labels:
      caddy: grafana.mafro.net
      caddy.tls.ca: https://ca.mafro.net:4433/acme/acme/directory
      caddy.tls.ca_root: /root/step_ca.crt
      caddy.reverse_proxy: "{{upstreams 3000}}"

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.cpufreq'
      - '--collector.diskstats'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.hwmon'
      - '--collector.loadavg'
      - '--collector.meminfo'
      - '--collector.netclass'
      - '--collector.netstat'
      - '--collector.stat'
      - '--collector.uname'
      - '--collector.vmstat'
      - '--collector.wifi'
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
