---
global:
  scrape_interval: 1m

remote_write:
  - url: http://prom-lts:9090/api/v1/write
    write_relabel_configs:
      - source_labels: [job]
        regex: 'ha'
        action: keep

scrape_configs:
  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['ringil:9100', 'locke:9100', 'jorg:9100']

  - job_name: 'ha'
    metrics_path: /api/prometheus

    authorization:
      credentials_file: /secrets/ha_token

    scheme: https
    static_configs:
      - targets: ['home.mafro.net']
